version: '3.8'

services:
  db:
    image: postgres:14
    container_name: weather_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: weather_db
    ports:
      - "5433:5432"
    networks:
      - weather-net

  server:
    build: .
    container_name: weather_server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - weather-net
    environment:
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: weather_db
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .:/app


networks:
  weather-net:
